spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: sa

  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true

springdoc.swagger-ui.path: /swagger-ui.html